spring:
  application:
    name: vg-ms-user
  data:
    mongodb:
      uri: mongodb+srv://huamantirado2006:1Cl61RtNEUNI2Pz0@cluster0.ahl0qgf.mongodb.net/PRS_proyect?retryWrites=true&w=majority&appName=Cluster0
  mail:
    host: smtp.gmail.com
    port: 587
    username: ${EMAIL_USERNAME:favio.huaman@vallegrande.edu.pe}
    password: ${EMAIL_PASSWORD:fsoq ldwg qvcd itpx}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
          ssl:
            trust: smtp.gmail.com
keycloak:
  server-url: "https://lab.vallegrande.edu.pe/school/ms-keycloak"
  realm-name: "auth-school"
  realm-master: "master"
  admin-cli: "admin-cli"
  user-console: "admin"
  password-console: "eduassist"
  client-secret: "moK3cebe2pBmxckugtkFVkDoNLm1D8iV"
server:
  port: 8100
